import com.project.droolsdemo.models.CarInsuranceDetails;
import java.lang.*;
import java.math.BigDecimal;

dialect "mvel" 


rule "BajajAllianz-Criteria Based on Manufacturing Date"
lock-on-active true
salience 10
	when
	    $carInfo:CarInsuranceDetails(manufacturedYear >= "2007" , $amt:cost)
	    $map:HashMap()
    then
    	System.out.println("RULE 1")
        $map.put("Bajaj Allianz",$amt)
        update($map)
        
end

rule "BajajAllianz-Criteria Based on Claims Number - 1"
no-loop true
	when
		$carInfo:CarInsuranceDetails(claims >= 1 && <3 , $amt:cost)	
		$map:HashMap(this["Bajaj Allianz"] != null)
		
	then
	System.out.println("RULE 2")
	    $amt=$amt*0.90
	    $map.put("Bajaj Allianz", $amt)
end
	
rule "BajajAllianz-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 , $amt:cost)	
		$map:HashMap(this["Bajaj Allianz"] != null)
		
	then
	System.out.println("RULE 3")
	    $amt=$amt*0.75
	    $map.put("Bajaj Allianz", $amt)
end   

rule "BajajAllianz-Criteria Based on Claims and Use - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,use == "business", $amt:cost)	
		$map:HashMap(this["Bajaj Allianz"] != null)
		
	then
	System.out.println("RULE 4")
	    $amt=$amt*0.5
	    $map.put("Bajaj Allianz", $amt)
end 


	   