import com.project.droolsdemo.models.CarInsuranceDetails;
import java.lang.*;
import java.math.BigDecimal;
import com.project.droolsdemo.models.Insurer;
 
 
ruleflow-group "Tata"
  
rule "MaxLife-Criteria Based on Manufacturing Date"

lock-on-active true
salience 10
dialect "java"

	when
	    $carInfo:CarInsuranceDetails(manufacturedYear >= "2010",profession =="Employed" , $amt:cost)
	    $list: ArrayList()
    then
    	System.out.println("Oriental RULE 1");
        modify($list){add(new Insurer("MaxLife",$amt*0.15,"15%"))};   
end



rule "MaxLife-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 2 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "MaxLife") from $list
	then
		System.out.println("MaxLife RULE 3")
	    $amt=$amt*0.10
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("10%")
end   

rule "MaxLife-Criteria Based on Claims and Use - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,use == "business", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "MaxLife") from $list
	then
		System.out.println("MaxLife RULE 4")
	    $amt=$amt*0.05
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("5%")
end 

rule "MaxLife-Criteria Based on City-1"
	when
		$carInfo:CarInsuranceDetails(city == "Bihar", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "MaxLife") from $list
	then
		System.out.println("MaxLife RULE 5")
	    $amt=$amt*0.05
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("5%")
end 


	   