import com.project.droolsdemo.models.CarInsuranceDetails;
import java.lang.*;
import java.math.BigDecimal;
import com.project.droolsdemo.models.Insurer;

dialect "mvel" 

ruleflow-group "Tata"

rule "National-Criteria Based on Manufacturing Date"
lock-on-active true
salience 10

dialect "java"
	when
	    $carInfo:CarInsuranceDetails(use == "personal",claims < 3 , $amt:cost)
	    $list: ArrayList()
    then
    	System.out.println("RULE 1");
    	$list.add(new Insurer("National",$amt*0.3,"30%"));
        update($list);
end

rule "National-Criteria Based on Claims Number - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 1 && <3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "National") from $list
	then
		System.out.println("RULE 2")
	    $amt=$amt*0.25
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("25%")
end
	
rule "National-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "National") from $list
	then
	System.out.println("RULE 3")
	    $amt=$amt*0.22
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("22%")
end   

rule "National-Criteria Based on Claims and Year - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,manufacturedYear < "2007", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "National") from $list
	then
	System.out.println("RULE 4")
	    $amt=$amt*0.27
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("27%")
end 

rule "National-Criteria Based on Cityr - 1"
	when
		$carInfo:CarInsuranceDetails(city == "Delhi", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "National") from $list
	then
	System.out.println("RULE 5")
	    $amt=$amt*0.20
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("20%")
end 
	   