import com.project.droolsdemo.models.CarInsuranceDetails;
import java.lang.*;
import java.math.BigDecimal;
import com.project.droolsdemo.models.Insurer;

dialect "mvel" 


rule "TATA-Criteria Based on Manufacturing Date"
lock-on-active true
salience 10
dialect "java"
	when
	    $carInfo:CarInsuranceDetails(use == "personal" , $amt:cost)
	    $list: ArrayList()
    then
    	System.out.println("RULE 1");
    	$list.add(new Insurer("TATA",$amt));
        update($list);
end

rule "TATA-Criteria Based on Claims Number - 1"
no-loop true
	when
		$carInfo:CarInsuranceDetails(claims >= 1 && <3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "TATA") from $list
	then
		System.out.println("RULE 2")
	    $amt=$amt*0.90
	    $insurer.setAmount($amt)
end
	
rule "TATA-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "TATA") from $list
	then
	System.out.println("RULE 3")
	    $amt=$amt*0.75
	    $insurer.setAmount($amt)
end   

rule "TATA-Criteria Based on Claims and Year - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,manufacturedYear < "2007", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "TATA") from $list
	then
	System.out.println("RULE 4")
	    $amt=$amt*0.40
	    $insurer.setAmount($amt)
end 

rule "TATA-Criteria Based on Claims and Year - 2"

	when
		$carInfo:CarInsuranceDetails(claims >= 5 ,manufacturedYear < "2000", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "TATA") from $list
	then
		System.out.println("RULE 5");
		$list.remove($insurer)
	    
end 
	   