import com.project.droolsdemo.models.CarInsuranceDetails;
import java.lang.*;
import java.math.BigDecimal;
import com.project.droolsdemo.models.Insurer;

dialect "mvel" 

ruleflow-group "default"

rule "TATA-Criteria Based on Manufacturing Date"
lock-on-active true
salience 10

dialect "java"
	when
	    $carInfo:CarInsuranceDetails(use == "personal" , $amt:cost)
	    $list: ArrayList()
    then
    	System.out.println("RULE 1");
    	$list.add(new Insurer("Tata",$amt*0.5,"50%"));
        update($list);
end

rule "TATA-Criteria Based on Claims Number - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 1 && <3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "Tata") from $list
	then
		System.out.println("RULE 2")
	    $amt=$amt*0.47
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("37%")
end
	
rule "TATA-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "Tata") from $list
	then
	System.out.println("RULE 3")
	    $amt=$amt*0.40
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("40%")
end   

rule "TATA-Criteria Based on Claims and Year - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,manufacturedYear < "2007", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "Tata") from $list
	then
	System.out.println("RULE 4")
	    $amt=$amt*0.35
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("35%")
end 

rule "TATA-Criteria Based on Claims and Year - 2"

	when
		$carInfo:CarInsuranceDetails(claims >= 5 ,manufacturedYear < "2000", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "Tata") from $list
	then
		System.out.println("RULE 5");
		$list.remove($insurer)
end 
	  

rule "TATA-Criteria Based on Claims and Gender - 1"

	when
		$carInfo:CarInsuranceDetails(claims >= 2 ,gender == "Female", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "Tata") from $list
	then
		System.out.println("RULE 6")
	    $amt=$amt*0.30
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("30%")
end 
	 