import com.project.droolsdemo.models.TaxiRide;
import com.project.droolsdemo.models.Fare;
import java.util.*;
import java.lang.*;

global com.project.droolsdemo.models.Fare rideFare;
dialect  "mvel"

rule "Calculate Taxi Fare - Scenario 1"
    when
    	$parameter:Boolean();
        taxiRideInstance:TaxiRide(isNightSurcharge == $parameter && distanceInMile < 10);
    then
    System.out.println($parameter);
       	rideFare.setNightSurcharge(0);
       	rideFare.setRideFare(70);
end

rule "Calculate Taxi Fare - Scenario 2"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile < 10);
    then
       	rideFare.setNightSurcharge(30);
       	rideFare.setRideFare(70);
end


rule "Calculate Taxi Fare - Scenario 3"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile >= 10 && distanceInMile < 100);
    then
       	rideFare.setNightSurcharge(0);
       	rideFare.setRideFare(70+(2*taxiRideInstance.getDistanceInMile()));
end


rule "Calculate Taxi Fare - Scenario 4"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile >= 10 && distanceInMile < 100);
    then
       	rideFare.setNightSurcharge(30+taxiRideInstance.getDistanceInMile());
       	rideFare.setRideFare(70+(2*taxiRideInstance.getDistanceInMile()));
end


rule "Calculate Taxi Fare - Scenario 5"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile >= 100);
    then
       	rideFare.setNightSurcharge(0);
       	rideFare.setRideFare(70+(1.5*taxiRideInstance.getDistanceInMile()));
end

rule "Calculate Taxi Fare - Scenario 6"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile >= 100);
    then
       	rideFare.setNightSurcharge(30+taxiRideInstance.getDistanceInMile());
       	rideFare.setRideFare(70+(1.5*taxiRideInstance.getDistanceInMile()));
end