import com.project.droolsdemo.models.CarInsuranceDetails;
import java.lang.*;
import java.math.BigDecimal;
import com.project.droolsdemo.models.Insurer;
 
 
ruleflow-group "Icici"
  
rule "United-Criteria Based on Manufacturing Date"

lock-on-active true
salience 10
dialect "java"

	when
	    $carInfo:CarInsuranceDetails(manufacturedYear >= "2007" , $amt:cost)
	    $list: ArrayList()
    then
    	System.out.println("United RULE 1");
    	//$list.add(new Insurer("Oriental",$amt));
        modify($list){add(new Insurer("United",$amt*0.25,"25%"))};   
end

rule "United-Criteria Based on Claims Number - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 1 && <3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "United") from $list
		
	then
		System.out.println("United RULE 2")
	    $amt=$amt*0.20
	   	$insurer.setAmount($amt)
	   	$insurer.setPercentage("20%")
	   	
end


rule "United-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "United") from $list
	then
		System.out.println("United RULE 3")
	    $amt=$amt*0.15
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("15%")
end   

rule "United-Criteria Based on Claims and Use - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,use == "business", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "United") from $list
	then
		System.out.println("United RULE 4")
	    $amt=$amt*0.10
	    $insurer.setAmount($amt)
	    $insurer.setPercentage("10%")
end 




	   